apiVersion: v1
kind: Service
metadata:
  name: svc-tasks-frontend
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3001
  selector:
    app: tasks
    tier: front
