apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-tasks-backend
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: public-gateway
    namespace: nginx-gateway
  hostnames:
  - "{{ required ".Values.host entry is required!" .Values.host }}"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: svc-tasks-backend
      port: 5000
