apiVersion: v1
kind: Service
metadata:
  name: svc-tasks-frontend
  namespace: <###namespace###>
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: tasks
    tier: frontend
