apiVersion: v1
kind: Service
metadata:
  name: svc-tasks-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: tasks
    tier: backend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: tasks
    tier: backend
