apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-tasks-frontend
  namespace: <###namespace###>
spec:
  parentRefs:
  - name: public-gateway
    namespace: nginx-gateway
  hostnames:
  - "<###host###>"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: svc-tasks-frontend
      port: 3000
