apiVersion: apps/v1
kind: Deployment

metadata:
  name: deploy-tasks-backend
  namespace: {{ .Release.Namespace }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: tasks
      tier: backend

  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 25%

  template:
    metadata:
      labels:
        app: tasks
        tier: backend

    spec:

      imagePullSecrets:
      - name: sec-cmregistry

      priorityClassName: business-app-critical

      containers:
      - image: {{ required ".Values.image entry is required!" .Values.image }}
        imagePullPolicy: Always
        name: tasks-backend

        envFrom:
          - configMapRef:
              name: cm-tasks-backend
        command: ["python"]
        args: ["app.py"]

        ports:
        - containerPort: 5000

        startupProbe:
          tcpSocket:
            port: 5000
          failureThreshold: 12
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          periodSeconds: 60
          failureThreshold: 1
          initialDelaySeconds: 0

        readinessProbe:
          httpGet:
            path: /api/config
            port: 5000
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 0
          timeoutSeconds: 5

        resources:
          requests:
            memory: "16M"
            cpu: "50m"
            ephemeral-storage: "512M"
          limits:
            memory: "128M"
            cpu: "500m"
            ephemeral-storage: "512M"
