firstname: Studentx
image: registry.creativemoods.pt/studentx/backend:previous
host: studentx-tasks.creativemoods.pt
otelEndpoint: otel-collector-opentelemetry-collector.tracing.svc.cluster.local:4317
