apiVersion: v1
kind: Service
metadata:
  name: svc-tasks-backend
  namespace: <###namespace###>
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: tasks
    tier: backend
  clusterIP: None
