apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-tasks-frontend
  namespace: <###namespace###>
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - <###host###>
    secretName: secret-tasks
  rules:
  # host rule will route traffic when the hostname requested matches
  - host: <###host###>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-tasks-frontend
            port:
              number: 3000
